'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, Building2, CheckCircle2, ChevronRight, Clock3, DollarSign, ShieldCheck, Utensils } from 'lucide-react';
import { clsx } from 'clsx';
import type { AuditCardData, Physician } from '@/lib/types';
import { getAuditCard } from '@/lib/api';
import { Spinner } from './Spinner';

interface AuditCardProps { physician: Physician; auditToken: string; onDispute: () => void; loadingDispute?: boolean; mobile?: boolean; }

export function AuditCard({ physician, onDispute, loadingDispute = false, mobile = false }: AuditCardProps) {
  const [auditData, setAuditData] = useState<AuditCardData | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); getAuditCard(physician.npi).then(setAuditData).catch(console.error).finally(() => setLoading(false)); }, [physician.npi]);
  if (loading) return <div className="grid min-h-[540px] place-items-center"><div className="text-center"><Spinner size={28} className="mx-auto" /><p className="mt-3 text-xs text-[var(--c-text-muted)]">Preparing payment review…</p></div></div>;

  const unreviewed = physician.payments.filter((payment) => !payment.reviewed);
  const surgeMonths = auditData?.velocity_summary.filter((summary) => summary.is_surge) ?? [];
  const topManufacturers = auditData?.top_manufacturers.slice(0, 2) ?? [];

  return <div className={clsx('bg-[var(--c-surface)]', mobile ? 'min-h-[calc(100dvh-96px)]' : '')}>
    <div className="border-b border-[var(--c-border)] bg-[linear-gradient(110deg,#0b3655,#0f6075)] px-5 py-5 text-white sm:px-6"><div className="flex items-center gap-2 text-xs text-[#c6f6ef]"><ShieldCheck size={15} /><span className="font-semibold">Secure clinician review</span><span className="ml-auto rounded-full border border-white/20 bg-white/10 px-2 py-0.5 text-[10px] font-medium">NPPES matched</span></div><h2 className="mt-4 text-xl font-bold tracking-[-.03em]">Dr. {physician.nppes.first_name} {physician.nppes.last_name}, {physician.nppes.credential}</h2><div className="mt-1 flex items-center gap-2 text-sm text-[#d6eaf0]"><span>{physician.nppes.primary_specialty}</span><span className="text-white/40">·</span><span>NPI {physician.npi}</span></div></div>
    <div className="space-y-5 p-5 sm:p-6">
      <div className="grid grid-cols-3 gap-2.5"><Stat icon={<DollarSign size={15} />} label="Reported total" value={`$${physician.total_amount.toLocaleString()}`} /><Stat icon={<Utensils size={15} />} label="Meals" value={String(physician.meal_count)} /><Stat icon={<Clock3 size={15} />} label="To review" value={String(physician.unreviewed_count)} emphasize={physician.unreviewed_count > 0} /></div>
      <div className="rounded-xl border border-[#22625f] bg-[#0d373a] p-3.5"><div className="flex items-start gap-2.5"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#78e3d7]" /><div><p className="text-sm font-semibold text-[#d7faf5]">Your review starts with the record.</p><p className="mt-0.5 text-xs leading-5 text-[var(--c-text-secondary)]">Compare each entry with your own records. A payment is not a finding; it is information that may need clarification.</p></div></div></div>
      {(physician.mismatch_score > .7 || surgeMonths.length > 0) && <div className="space-y-2"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[var(--c-text-muted)]">Items worth a closer look</p>{physician.mismatch_score > .7 && <SignalCard title="Specialty Mismatch Detected" copy={`${Math.round(physician.mismatch_score * 100)}% semantic distance between the listed product and your registered specialty.`} tone="red" />}{surgeMonths.length > 0 && <SignalCard title="Unusual reporting pattern" copy={`${surgeMonths.length} period${surgeMonths.length > 1 ? 's show' : ' shows'} a higher-than-usual frequency of reported payments.`} tone="amber" />}</div>}
      {unreviewed.length > 0 ? <div><div className="mb-2.5 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[var(--c-text-muted)]">Awaiting your review</p><p className="mt-1 text-sm font-semibold text-[var(--c-text-primary)]">{unreviewed.length} reported item{unreviewed.length > 1 ? 's' : ''}</p></div><span className="text-xs text-[var(--c-text-muted)]">{physician.nppes.address.city}, {physician.nppes.address.state}</span></div><div className="space-y-2">{unreviewed.map((payment) => <div key={payment.id} className="flex items-center justify-between gap-3 rounded-xl border border-[var(--c-border)] bg-[#0b202b] p-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[var(--c-text-primary)]">{payment.manufacturer}</p><p className="mt-0.5 text-xs text-[var(--c-text-muted)]">{payment.nature_of_payment} · {payment.payment_date}</p></div><div className="text-right"><p className="font-mono text-sm font-semibold text-[var(--c-text-primary)]">${payment.amount.toLocaleString()}</p>{payment.mismatch_score > .7 && <p className="mt-0.5 text-[11px] font-medium text-[#ed7b76]">Mismatch signal</p>}</div></div>)}</div></div> : <div className="rounded-xl border border-[var(--c-border)] bg-[var(--c-bg-secondary)] p-5 text-center"><CheckCircle2 size={22} className="mx-auto text-[#78e3d7]" /><p className="mt-2 text-sm font-semibold text-[var(--c-text-primary)]">No items currently await review.</p></div>}
      {topManufacturers.length > 0 && <div className="rounded-xl bg-[var(--c-bg-secondary)] p-3.5"><div className="flex items-center gap-2"><Building2 size={14} className="text-[var(--c-text-muted)]" /><p className="text-xs font-semibold uppercase tracking-[.12em] text-[var(--c-text-muted)]">Reporting organizations</p></div><div className="mt-3 grid grid-cols-2 gap-2">{topManufacturers.map((manufacturer) => <div key={manufacturer.name} className="rounded-lg bg-[#102d39] px-3 py-2"><p className="truncate text-xs font-medium text-[var(--c-text-primary)]">{manufacturer.name}</p><p className="mt-1 font-mono text-xs text-[var(--c-text-secondary)]">${manufacturer.total_amount.toLocaleString()}</p></div>)}</div></div>}
      {unreviewed.length > 0 && <div className="border-t border-[var(--c-border)] pt-5"><button onClick={onDispute} disabled={loadingDispute} className={clsx('flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3.5 text-sm font-semibold transition', loadingDispute ? 'cursor-not-allowed bg-[#17323d] text-[var(--c-text-muted)]' : 'bg-[#3bd0bd] text-[#071720] hover:bg-[#78e3d7] glow-green')}>{loadingDispute ? <><Spinner size={16} className="text-white" />Preparing notice…</> : <>Dispute unreviewed items <ChevronRight size={16} /></>}</button><p className="mt-2 text-center text-[11px] leading-4 text-[var(--c-text-muted)]">This prepares a formal notice for your review under 42 CFR § 403.908.</p></div>}
    </div>
  </div>;
}

function Stat({ icon, label, value, emphasize = false }: { icon: React.ReactNode; label: string; value: string; emphasize?: boolean }) { return <div className={clsx('rounded-xl border p-3', emphasize ? 'border-[#775c28] bg-[#302714]' : 'border-[var(--c-border)] bg-[#0b202b]')}><div className={clsx('mb-2', emphasize ? 'text-[#f4c46e]' : 'text-[#78e3d7]')}>{icon}</div><p className={clsx('truncate font-mono text-base font-bold', emphasize ? 'text-[#f4c46e]' : 'text-[var(--c-text-primary)]')}>{value}</p><p className="mt-0.5 text-[11px] text-[var(--c-text-muted)]">{label}</p></div>; }
function SignalCard({ title, copy, tone }: { title: string; copy: string; tone: 'red' | 'amber' }) { const red = tone === 'red'; return <div className={clsx('flex gap-2.5 rounded-xl border p-3', red ? 'border-[#663d42] bg-[#351f28]' : 'border-[#705c33] bg-[#302714]')}><AlertTriangle size={16} className={clsx('mt-0.5 shrink-0', red ? 'text-[#ed7b76]' : 'text-[#f4c46e]')} /><div><p className={clsx('text-xs font-semibold', red ? 'text-[#f5aaa5]' : 'text-[#f4c46e]')}>{title}</p><p className="mt-0.5 text-xs leading-5 text-[var(--c-text-secondary)]">{copy}</p></div></div>; }
